name: Update python SDK

on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update_python_sdk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # 1. Спочатку конфігуруємо Git і підтягуємо зміни
      - name: Pull latest changes
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git pull --rebase origin main

      # 2. Тепер завантажуємо архів
      - name: Download python.tgz
        run: |
          curl -L -o python.tgz https://app.api2cart.com/sdk/openapi/python.tgz

      # 3. Розпаковуємо
      - name: Extract python.tgz
        run: |
          tar -xzf python.tgz --strip-components=1

      # 4. Додаємо зміни, комітимо і пушимо
      - name: Commit and push changes
        run: |
          git add .
          git diff-index --quiet HEAD || git commit -m "Update python SDK [skip ci]"
          git push origin HEAD:main
